-- Application user
CREATE USER ${CPPCHAT_DB_USER} WITH PASSWORD '${CPPCHAT_DB_PSSWD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${CPPCHAT_DB_USER};
GRANT USAGE ON SCHEMA public TO ${CPPCHAT_DB_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${CPPCHAT_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${CPPCHAT_DB_USER};

-- Grafana read-only user
CREATE USER grafana WITH PASSWORD '${GRAFANA_DB_PSSWD}';
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO grafana;
GRANT USAGE ON SCHEMA public TO grafana;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT ON TABLES TO grafana;