version: '3.8'

services:
  elasticsearch:

    build:
      context: ./docker/elasticsearch
      args:
        - ES_VERSION=${ES_VERSION}
    container_name: ${PROJECT}-elasticsearch
    ports:
      - ${ES_PORT}:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=${ES_SECURITY}
      - ELASTIC_PASSWORD=${ES_PSSWD}
      - KIBANA_SYS_PSSWD=${KIBANA_SYS_PSSWD}
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s -u elastic:${ES_PSSWD} http://localhost:9200 >/dev/null || exit 1
      interval: 5s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  kibana:
    image: kibana:${ES_VERSION}
    container_name: ${PROJECT}-kibana
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:${ES_PORT}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYS_PSSWD}
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  esdata: