version: '3.9'

volumes:
  grafana-data:
    name: ${PROJECT}_grafana_data
  loki-data:
    name: ${PROJECT}_loki_data

networks:
  cppchat:
    driver: bridge

services:
  loki:
    image: grafana/loki:3.5.0
    container_name: ${PROJECT}-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - cppchat
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 10s
      retries: 5
      start_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}

  promtail:
    image: grafana/promtail:3.5.0
    container_name: ${PROJECT}-promtail
    volumes:
      - ./logs:/var/log/cppchat:ro
      - ./docker/promtail/promtail-config.yaml:/etc/promtail/config.yml
    networks:
      - cppchat
    depends_on:
      loki:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      - USER=${PROMTAIL_USER}
      - PSSWD=${PROMTAIL_PSSWD}

  grafana:
    image: grafana/grafana-oss:12.0.0
    container_name: ${PROJECT}-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - cppchat
    depends_on:
      loki:
        condition: service_healthy
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_LOG_LEVEL=info
      - TZ=${TZ:-UTC}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT}-nginx
    ports:
      - "3101:3101"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - cppchat
    depends_on:
      loki:
          condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    restart: unless-stopped