server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push
    basic_auth:
      username: ${USER}
      password: ${PSSWD}

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: cppchat
    static_configs:
      - targets:
          - localhost
        labels:
          job: cppchat
          __path__: /var/log/cppchat/cppchat.log