server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    basic_auth:
      username: ${USER:-promtail}
      password: ${PSSWD:-}

scrape_configs:
  - job_name: cppchat
    static_configs:
      - targets:
          - localhost
        labels:
          job: cppchat
          __path__: /var/log/cppchat/*.log

    pipeline_stages:
      - match:
          selector: '{job="cppchat"}'
          stages:
            - regex:
                expression: '\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\] \[(?P<level>[a-zA-Z]+)\]'
            - labels:
                level: